function build_trace_links()
%BUILD_TRACE_LINKS Create the traceability links (Requirements Toolbox link sets).
%   Derive     SWR-<PFX>-NNN      -> SYS-SR-NNN     (from the SWR ParentSysSR attribute)
%   Implement  architecture component RoverPlatformArch/<Subsystem>/<package> -> its SWRs
%   Verify     test method in tests/t*.m -> the IDs on its "% Verifies:" line
%   Only links carrying the marker below are replaced, so links added by hand in the
%   Requirements Editor survive a re-run. The test link sets (tests/t*~m.slmx) hold
%   generated links only and are rebuilt, so edited test files never keep stale ranges.

% Copyright 2026 Mechatronics Academy
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%     http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

marker = 'generated by build_trace_links';
root = mbse.root();
slreq.clear();
old = dir(fullfile(root, 'tests', 't*~m.slmx'));
for k = 1:numel(old)
    delete(fullfile(old(k).folder, old(k).name));
end
sysSet = slreq.load(fullfile(root, 'requirements', 'ROVER_ROS_SYS-SR.slreqx'));
swFiles = dir(fullfile(root, 'requirements', 'SWRS_*.slreqx'));
swSets = cell(1, numel(swFiles));
for k = 1:numel(swFiles)
    swSets{k} = slreq.load(fullfile(swFiles(k).folder, swFiles(k).name));
end
arch = mbse.readJson(fullfile('data', 'platform_architecture.json'));
model = systemcomposer.loadModel('RoverPlatformArch');

% Remove the previously generated links
ls = slreq.find('type', 'LinkSet');
nRemoved = 0;
for k = 1:numel(ls)
    links = ls(k).getLinks();
    for j = 1:numel(links)
        if strcmp(links(j).Description, marker)
            links(j).remove();
            nRemoved = nRemoved + 1;
        end
    end
end

byId = containers.Map();
reqs = sysSet.find('Type', 'Requirement');
for j = 1:numel(reqs)
    byId(reqs(j).Id) = reqs(j);
end
for k = 1:numel(swSets)
    reqs = swSets{k}.find('Type', 'Requirement');
    for j = 1:numel(reqs)
        byId(reqs(j).Id) = reqs(j);
    end
end

%% Derive: SWR -> SYS-SR
nDerive = 0;
for k = 1:numel(swSets)
    reqs = swSets{k}.find('Type', 'Requirement');
    for j = 1:numel(reqs)
        parents = strtrim(strsplit(reqs(j).getAttribute('ParentSysSR'), ','));
        for p = 1:numel(parents)
            if isempty(parents{p})
                continue
            end
            makeLink(reqs(j), byId(parents{p}), 'Derive', marker);
            nDerive = nDerive + 1;
        end
    end
end

%% Implement: architecture component -> SWR
comp2sub = containers.Map();
for k = 1:numel(arch.composites)
    members = cellstr(arch.composites(k).members);
    for m = 1:numel(members)
        comp2sub(members{m}) = arch.composites(k).name;
    end
end
nImpl = 0;
for k = 1:numel(arch.components)
    c = arch.components(k);
    comp = model.lookup('Path', ['RoverPlatformArch/' comp2sub(c.name) '/' c.name]);
    swSet = swSets{strcmp({swFiles.name}, ['SWRS_' c.prefix '.slreqx'])};
    reqs = swSet.find('Type', 'Requirement');
    for j = 1:numel(reqs)
        makeLink(comp, reqs(j), 'Implement', marker);
        nImpl = nImpl + 1;
    end
end

%% Verify: test methods -> requirements
nVerify = 0;
for v = mbse.testVerifies()
    range = slreq.createTextRange(v.file, [v.fnLine v.tagLine]);
    for p = 1:numel(v.ids)
        if ~isKey(byId, v.ids{p})
            error('build_trace_links:unknownId', '%s verifies unknown %s', v.name, v.ids{p});
        end
        makeLink(range, byId(v.ids{p}), 'Verify', marker);
        nVerify = nVerify + 1;
    end
end

ls = slreq.find('type', 'LinkSet');
for k = 1:numel(ls)
    ls(k).save();
end
fprintf('build_trace_links: removed %d, created %d derive, %d implement, %d verify links\n', ...
    nRemoved, nDerive, nImpl, nVerify);
slreq.clear();
close_system('RoverPlatformArch', 0);
end

function makeLink(src, dst, type, marker)
link = slreq.createLink(src, dst);
link.Type = type;
link.Description = marker;
end
