function build_skid_steer()
%BUILD_SKID_STEER Executable as-built model of the skid-steer kinematics and odometry.
%   behaviour/SkidSteerKinematics.slx, 50 Hz (diff_drive_controller update rate):
%     InverseKinematics - body twist -> 4 wheel joint velocities (2 wheels per side),
%                         effective track = wheel_separation * wheel_separation_multiplier;
%                         wheel_velocity_limited flags a joint above the URDF limit.
%     Wheels            - ASSUMPTION: ideal wheel velocity tracking (no PID lag, no slip).
%                         The measured ground behaviour differs (see the memory note on
%                         wheel PID ground authority); this model verifies the kinematic
%                         design, not the traction.
%     Odometry          - forward kinematics + pose integration, as diff_drive does.

name = 'SkidSteerKinematics';
file = mbse.newModel(name, 0.02);
P = mbse.paramStruct({'wheel_radius', 'wheel_separation', 'wheel_separation_multiplier', ...
    'wheel_joint_velocity_limit', 'diff_drive_update_rate'});
P.dt = 0.02;
assignin(get_param(name, 'ModelWorkspace'), 'P', P);

ikCode = strjoin({
    'function [w_fl, w_fr, w_rl, w_rr, rim_speed_max, wheel_velocity_limited] = InverseKinematics(vx, wz, P)'
    'track = P.wheel_separation * P.wheel_separation_multiplier;'
    'w_left = (vx - wz * track / 2) / P.wheel_radius;'
    'w_right = (vx + wz * track / 2) / P.wheel_radius;'
    'w_fl = w_left; w_rl = w_left; w_fr = w_right; w_rr = w_right;'
    'rim_speed_max = max(abs([w_left w_right])) * P.wheel_radius;'
    'wheel_velocity_limited = double(max(abs([w_left w_right])) > P.wheel_joint_velocity_limit);'
    }, newline);
mbse.addFcn([name '/InverseKinematics'], ikCode, {'P'}, [300 60 480 220]);

odoCode = strjoin({
    'function [x, y, yaw, v_odom, wz_odom, distance] = Odometry(w_fl, w_fr, w_rl, w_rr, P)'
    'persistent px py pyaw pdist'
    'if isempty(px), px = 0; py = 0; pyaw = 0; pdist = 0; end'
    'track = P.wheel_separation * P.wheel_separation_multiplier;'
    'w_left = (w_fl + w_rl) / 2; w_right = (w_fr + w_rr) / 2;'
    'v_odom = P.wheel_radius * (w_left + w_right) / 2;'
    'wz_odom = P.wheel_radius * (w_right - w_left) / track;'
    'px = px + v_odom * cos(pyaw + wz_odom * P.dt / 2) * P.dt;'
    'py = py + v_odom * sin(pyaw + wz_odom * P.dt / 2) * P.dt;'
    'pyaw = pyaw + wz_odom * P.dt;'
    'pdist = pdist + abs(v_odom) * P.dt;'
    'x = px; y = py; yaw = pyaw; distance = pdist;'
    }, newline);
mbse.addFcn([name '/Odometry'], odoCode, {'P'}, [640 60 820 220]);

for k = 1:4
    add_line(name, ['InverseKinematics/' num2str(k)], ['Odometry/' num2str(k)], 'autorouting', 'on');
end
ins = {'vx', 'wz'};
for k = 1:2
    y = 60 + (k - 1) * 40;
    add_block('simulink/Sources/In1', [name '/' ins{k}], 'Position', [120 y 150 y + 14], ...
        'Interpolate', 'off');
    add_line(name, [ins{k} '/1'], ['InverseKinematics/' num2str(k)], 'autorouting', 'on');
end
outs = {'w_fl', 'InverseKinematics/1'; 'w_fr', 'InverseKinematics/2'; ...
        'rim_speed_max', 'InverseKinematics/5'; 'wheel_velocity_limited', 'InverseKinematics/6'; ...
        'x', 'Odometry/1'; 'y', 'Odometry/2'; 'yaw', 'Odometry/3'; ...
        'v_odom', 'Odometry/4'; 'wz_odom', 'Odometry/5'; 'distance', 'Odometry/6'};
for k = 1:size(outs, 1)
    y = 40 + (k - 1) * 35;
    add_block('simulink/Sinks/Out1', [name '/' outs{k, 1}], 'Position', [980 y 1010 y + 14]);
    h = add_line(name, outs{k, 2}, [outs{k, 1} '/1'], 'autorouting', 'on');
    set_param(h, 'Name', outs{k, 1});
end

set_param(name, 'Description', ['As-built skid-steer kinematics (rover_controller diff_drive). ' ...
    'Generated by scripts/build_skid_steer.m.']);
save_system(name, file);
close_system(name, 0);
fprintf('build_skid_steer: %s\n', file);
end
