bool gpio_pin_hw_e_stop_user_button             # GPIO_HW_E_STOP_USER_BTN
bool gpio_pin_motor_contactor_engaged           # GPIO_MOTOR_CONTACTOR_ENGAGED
bool gpio_pin_sw_e_stop_cpu_wdg_trigger         # GPIO_SW_E_STOP_CPU_WDG_TRIGGER
bool gpio_pin_sw_e_stop_user_button             # GPIO_SW_E_STOP_USER_BUTTON
bool gpio_pin_sw_e_stop_motor_driver_fault      # GPIO_SW_E_STOP_MOTOR_DRIVER_FAULT
bool gpio_pin_sw_e_stop_latch_reset             # GPIO_SW_E_STOP_LATCH_RESET
bool gpio_pin_sw_e_stop_latch_status            # GPIO_SW_E_STOP_LATCH_STATUS