panels:
  - channel: 1
    number_of_leds: 24

segments:
  - name: front_1
    channel: 1
    led_range: 0-11
  - name: front_2
    channel: 1
    led_range: 23-12

segments_map:
  all: [front_1, front_2]

led_animations:
  - id: 0
    name: E_STOP
    priority: 3
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/e_stop.png
          duration: 6
      
  - id: 1
    name: READY
    priority: 3
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/ready.png
          duration: 6
      
  - id: 2
    name: ERROR
    priority: 0
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/error.png
          duration: 2
          repeat: 2

  - id: 3
    name: NO_ERROR
    priority: 0
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/empty.png
          duration: 1
          repeat: 1

  - id: 5
    name: LOW_BATTERY
    priority: 2
    animations:
      - type: husarion_ugv_lights::MovingImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/low_battery.png
          duration: 10
          repeat: 1
          center_offset: 24
          object_width: 2
          splash_duration: 10.0

  - id: 6
    name: CRITICAL_BATTERY
    priority: 2
    animations:
      - type: husarion_ugv_lights::MovingImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/critical_battery.png
          duration: 10
          repeat: 1
          center_offset: 24
          object_width: 2
          splash_duration: 10.0

  - id: 7
    name: CHARGING_BATTERY
    priority: 2
    animations:
      - type: husarion_ugv_lights::MovingImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/charging_battery.png
          duration: 10
          repeat: 1
          center_offset: 38
          object_width: 1
          splash_duration: 10.0

  - id: 8
    name: BATTERY_CHARGED
    priority: 2
    animations:
      - type: husarion_ugv_lights::MovingImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/battery_charged.png
          duration: 10
          repeat: 1
          center_offset: 38
          object_width: 1
          splash_duration: 10.0

  - id: 9
    name: CHARGER_INSERTED
    priority: 1
    animations:
      - type: husarion_ugv_lights::ImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/charger_inserted.png
          duration: 8

  - id: 10
    name: BATTERY_NOMINAL
    priority: 2
    animations:
      - type: husarion_ugv_lights::ImageAnimation
        segments: all
        animation:
          image: $(find husarion_ugv_lights)/animations/panther/empty.png
          duration: 1
          repeat: 1