panels:
  - channel: 1
    number_of_leds: 24

segments:
  - name: front_1
    channel: 1
    led_range: 0-11
  - name: front_2
    channel: 1
    led_range: 23-12

segments_map:
  all: [front_1, front_2]

led_animations:
  - id: 0
    name: E_STOP
    priority: 3
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/e_stop.png
          duration: 6
      
  - id: 1
    name: READY
    priority: 3
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/ready.png
          duration: 6
      
  - id: 2
    name: ERROR
    priority: 0
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/error.png
          duration: 2
          repeat: 2

  - id: 3
    name: NO_ERROR
    priority: 0
    animations:
      - type: rover_led::ImageAnimation
        segments: all
        animation:
          image: $(find rover_led)/animations/rover_a1/empty.png
          duration: 1
          repeat: 1